### ISSUE TITLE
[DESIGN] Initial Design Document. 

### ISSUE THREAD

**Issue by XavierSchiller** [XavierSchiller/OsuIndiaBotJS#16]
**Link to design document:** [Design Document.](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document)

**Comment by sabarnac** [comment]
* Add administrators and standard users under [**Actors**](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#actors) as well.
* Add the [**Use Case**](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#use-cases) for standard users opting in and out of being shown from the top feeds.
* Remove [extra **General** sub-heading](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#general).
* Define what the default values are for optional arguments in [**API Definition**](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#api-definition)
* Rename [**API Definition**](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#api-definition) to **Commands Definition**
* For `recent` command in [**API Definition**](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#api-definition), provide a note for the definition of **_recent_** is, since you have a possible failure state `"No recent Play for <user>."`.
* For `recent` command in [**API Definition**](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#api-definition), success result should be recent scores of user, not user information.
* For `osuset` command in [**API Definition**](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#api-definition), the description should be `Validates and attaches provided Osu user ID to the Discord ID of the requester`.
* Add command definition to provide user an option to unset their Osu ID?
* For `lb` command in [**API Definition**](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#api-definition), description states `the last map searched`. This requires a bit more context. Is it the last searched for the user making the request, the last searched of any user in the server, the last searched of any user in any server?
* For `lb` command in [**API Definition**](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#api-definition), change failure state `No Users Set: "Users not set for Leader Board."` to `No tracked users: "No tracked users present in leaderboard"`.
* For `track` command in [**API Definition**](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#api-definition), change description to `"Tracks requesting user to be shown in leaderboards"`.
* For `track` command in [**API Definition**](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#api-definition), state if tracking is enabled or disabled by default when a user attaches their Osu ID. We can have a discussion about this.
* For `track` command in [**API Definition**](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#api-definition), change failure state name `User Not Valid` to `User Osu ID not set`.
* For administrative command in [**API Definition**](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#api-definition), failure states related to privileges should have an empty error message, meaning that the bot will ignore commands from users who don't have the correct privileges to execute those commands.
* For `setfeedchannel` command in [**API Definition**](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#api-definition), rename to `setfeed`.
* For `setfeedchannel` command in [**API Definition**](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#api-definition), change description to `Attaches feed to channel that the command is executed in`.
  * It appears that [this npm package](https://www.npmjs.com/package/eris-additions) may provide context on the channel the message was sent from, iof not available already.
  * If channel context can not be retrieved, then accept an argument for a channel ID.
* For `resetfeed` command in [**API Definition**](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#api-definition), change description to `Resets tracked users list for feed`.
* For `removefeed` command in [**API Definition**](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#api-definition), change description to `Detaches feed from attached channel`.
* Add link to this issue at the top of the design document, in the section that is provided for it.
* nit: Some places have unnecessary capitalization. Undo them
  * ![Example 1](https://user-images.githubusercontent.com/11596438/57715867-4fa61580-7695-11e9-805d-1b34538a8b78.png)
  * ![Example 2](https://user-images.githubusercontent.com/11596438/57715869-4fa61580-7695-11e9-8197-07d786734002.png)

**Comment by XavierSchiller** [comment]
Changes Done.

**Comment by sabarnac** [comment]
1. Add the [**Use Case**](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#use-cases) for users tracking and untracking themselves from the feed .
1. In the [**Use Case**](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#use-cases) section. current  administrative use cases only talk about attaching and detaching the bot from a channel by the looks of it. Modify them to include that they also attach and detach the feed, and add the use case for resetting the feed.
1. For `recent` command in [**API Definition**](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#api-definition), remove the failure state `User Has No Scores`.
1. For `track` command in [**API Definition**](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#api-definition), either accept a param `[y|n]` for whether the user wishes to be tracked or not, or add a new command `untrack` to the commands list.
1. Comment 13 of [previous reply](https://github.com/XavierSchiller/OsuIndiaBotJS/issues/16#issuecomment-492325315)

**Comment by sabarnac** [comment]
1. For `unset` command in [**API Definition**](https://github.com/XavierSchiller/OsuIndiaBotJS/wiki/Design-Document#api-definition), rename to `osuunset` to line up with `osuset`.

Everything else is fine. You can continue with finishing the document.
